Final review
KenJamesHioki/weather_app pull request #16
Opened 2024-03-22 08:33 UTC by KenJamesHioki

コードの納品をします。
レビューお願いします。

2024-03-22 10:46 UTC, cyndiii29 requested changes
お疲れ様でした！
UI/UX非常に練られていて良いのではないかと思います！

まずはジャブ程度の指摘から入ります

2024-03-22 10:46 UTC, cyndiii29 commented on main.js
> +      return;
[MUST]
400系のエラーと500系のエラーをまとめて同じエラーメッセージを表示しているのはユーザーに誤解が生じます
500系エラーの場合はAPI側に問題があるので時間をおくことで解決する可能性はあると思いますが、400系のエラーの場合はそうはいきません

2024-03-22 10:46 UTC, cyndiii29 commented on main.js
> +      }));  ////ここを変更する必要あり
[Q] このコメントはなんですか？？

2024-03-22 10:53 UTC, cyndiii29 commented on main.js
> +  _init() {
[Q]
メソッドのprefixに_をつけているのはなぜですか？？

2024-03-25 10:36 UTC, KenJamesHioki commented on main.js
> +      return;
400系はAPIキーやAPIの叩き方が間違っている場合に発生するエラーだと認識しています。
エンドユーザーからするとAPIの叩き方が違うというようなメッセージは関心がないと思ったため、現行のメッセージ内容にし、consoleでは何系のエラーかを表示する実装にしています。
ただ、時間をおいても解決する内容でもないというのは確かにそうなので以下のコメントが表示されるように変更をしておきます。
「天気情報が取得できませんでした。」

2024-03-25 10:36 UTC, KenJamesHioki commented on main.js
> +      }));  ////ここを変更する必要あり
自分用に取っていたメモを消し忘れていたので、コメントを削除しておきます。

2024-03-25 10:48 UTC, KenJamesHioki commented on main.js
> +  _init() {
内部のみで使用するメソッドはプライベートメソッドだと分かるように_をつけています。
#を使う案もありましたが、対応ブラウザを決めていなかったため、_にしています。
最新版ブラウザへの対応のみということであれば#に変更しておきます。

2024-03-25 11:45 UTC, KenJamesHioki commented on main.js
> +      return;
@cyndiii29 
400系のエラーハンドリングをするクラスを作り問題点を修正しました。
確認お願いします。

2024-03-25 11:45 UTC, KenJamesHioki commented on main.js
> +      }));  ////ここを変更する必要あり
@cyndiii29 
コメントを削除したので確認お願いします。

2024-03-26 02:04 UTC, cyndiii29 commented on main.js
> +  _init() {
_にしただけでは外部からアクセスできてしまうのでプライベートにはなりません
プラベートメソッドにしたい場合は#をつけるべきです

2024-03-26 02:07 UTC, cyndiii29 commented on main.js
> +      return;
> 400系はAPIキーやAPIの叩き方が間違っている場合

クライアント側のエラーですね
400系のエラーにもいろいろ種類があるとおもっており、たとえば404 NotFoundだと、入力した都市名が存在しないなどユーザー側に問題があるケースはあります
エラーコードによって表示する内容は変更されうるべきです

2024-03-26 02:14 UTC, cyndiii29 commented on main.js
> +      return;
813436b8e07829bae12f4751624d6345bda9e432

全部400系エラーでハンドリングすべきではないですね
エラーコードによっては表示は変わってくるはずです
400,401,404,429 それぞれ原因は異なっていて、原因によってはユーザー側に問題がある可能性もありますよね？？

2024-03-26 02:14 UTC, cyndiii29 commented on main.js
> +      return;
@KenJamesHioki

2024-03-26 02:17 UTC, cyndiii29 reviewed
[MUST]
コメントがいっぱい書いてあるのですが果たして全て必要でしょうか？？
ちょうどいまコードを綺麗に書く系の座学をやっていると思うので、その辺を踏まえてアウトプットしてみましょう！
@KenJamesHioki

2024-03-26 02:28 UTC, cyndiii29 commented on main.js
> +  _init() {
あと、なぜプライベートメソッドにしたのでしょうか？
外部から実装にアクセスされると何かまずいのでしょうか？？

2024-03-26 02:37 UTC, cyndiii29 commented on main.js
> +  _init() {
[memo]
面談でclassの再利用性、カプセル化について話す

2024-03-26 05:02 UTC, KenJamesHioki commented on main.js
> +      return;
@cyndiii29 
各エラーコードに応じて適切なエラーメッセージを表示するように変更します。

2024-03-26 05:04 UTC, KenJamesHioki commented on main.js
> +  _init() {
@cyndiii29 
変更を加える前にプライベート変数にする理由を考えてみます。
自分の中で理由が明確になってから変更するかしないかを決めます。

2024-03-26 06:10 UTC, KenJamesHioki commented
> [MUST] コメントがいっぱい書いてあるのですが果たして全て必要でしょうか？？ ちょうどいまコードを綺麗に書く系の座学をやっていると思うので、その辺を踏まえてアウトプットしてみましょう！ @KenJamesHioki

@cyndiii29 
まずは大幅修正をせずに変更できる部分を修正しました。

2024-03-26 06:57 UTC, cyndiii29 commented on main.js
> +    this.APIKEY = '16806dd9a591b25a5beebeb69dd718b8';
[MUST]
大文字にしたということは定数にしたということですが、
constructorから渡ってくる時点でこの値は定数になり得ないので実装が矛盾してます！

2024-03-26 07:13 UTC, cyndiii29 commented on main.js
> +  // 複数の候補が返って来た場合はユーザーに選択させる方法がベストと考えた
[IMO]
後半のお気持ちコメントは不要なコメントですね。一般的な実装とかけ離れた実装をしていた場合はこのようなwhyのお気持ちコメントを入れることにより、別のエンジニアが事情を把握できるようにすることはあったりします
今回はコードを見ればわかるのと、どちらかというと仕様書ベースの話なのでソースコードにコメントに残さなくて良いかなと思います。

書くんだったら以下くらいの感じかな
```
// 複数都市の天気情報が返却された場合、複数都市の候補をユーザーに選択させる
```

2024-03-26 07:16 UTC, cyndiii29 commented on main.js
> +      if (location.local_names && location.local_names.ja) {
[Q]
この条件分岐はなぜ必要なのですか？？

2024-03-26 07:43 UTC, cyndiii29 commented on main.js
> +    coordArr.forEach(location => {
配列に対する操作にかんしてforeach & 空の配列にpushを多用されてますが、mapの方が好ましいです
https://qiita.com/diescake/items/70d9b0cbd4e3d5cc6fce

push()は破壊的なメソッドなので最近の開発では積極的につかわないです！
全体的に書き換えてみましょう！

2024-03-26 09:32 UTC, KenJamesHioki commented on main.js
> +      return;
@cyndiii29 
想定されるエラーコードは以下の通り。
401：API KEYの不備
404：存在しない都市名を入力している or APIのフォーマット不備
429：APIコール数の上限に達している
500, 502, 503 or 504：ベンダーに要問い合わせ

404の「存在しない都市名を入力している」は別の実装で拾って適切ない対処をしているため、400系のエラーはAPI起因に制限されます。そのため、400系のエラーが出た場合のエンドユーザーに表示するメッセージは「天気情報が取得できませんでした。」のみで良いと考えてます。

ただしどのエラーなのかが分かるようメッセージの後に（エラーコード：〇〇）と表示するように実装を変更します。

2024-03-26 09:52 UTC, KenJamesHioki commented on main.js
> +      return;
@cyndiii29 
400系の場合は「天気情報が取得できませんでした。（エラーコード：〇〇）」と表示するよう変更しました。
またtry...catch内のコードが2箇所で重複していたため関数として切り出しました。

2024-03-26 09:57 UTC, KenJamesHioki commented on main.js
> +    this.APIKEY = '16806dd9a591b25a5beebeb69dd718b8';
@cyndiii29 
指摘いただいたポイントは修正必須ですね。
指摘ポイントからは少しずれますが、併せてAPIキーを隠す必要もあると思っています。
.envファイルにAPIキーを入れておき、main.jsのクラス外で定数として持っておく方法で実装を進めてみます。
https://qiita.com/okonomiyaki11/items/41d86a113475490408e3

2024-03-26 10:00 UTC, KenJamesHioki commented on main.js
> +  // 複数の候補が返って来た場合はユーザーに選択させる方法がベストと考えた
@cyndiii29 
> // 複数都市の天気情報が返却された場合、複数都市の候補をユーザーに選択させる
これくらいの内容であればもはや必要なさそうですね。。。

APIを試した挙動の結果を残す目的でコメントを書きましたが、それすらコメントとしては必要ないという理解であっています？

2024-03-26 10:07 UTC, KenJamesHioki commented on main.js
> +      if (location.local_names && location.local_names.ja) {
@cyndiii29 
なるべく都市名を日本語名で表示をしたいからです。

APIで返却される都市の情報にlocal_names（各国の言語の都市名）が含まれるかは都市次第、更にその中にlocal_names.ja（日本語名）が含まれるかも都市次第なので、この分岐を追加しています。
どちらも存在しない場合は、必ず含まれるlocation.nameを採用するようにしています。

この背景がコードだけだと分かりづらいと思うのでコメントで追加しておきます。

併せてリファクタリングができるか検討します。

2024-03-26 10:45 UTC, KenJamesHioki commented on main.js
> +      if (location.local_names && location.local_names.ja) {
@cyndiii29 
・分岐を入れて理由をコメントで追加
・重複しているコードを別メソッドに切り出しました

2024-03-26 11:17 UTC, KenJamesHioki commented on main.js
> +    coordArr.forEach(location => {
@cyndiii29 
mapを使って修正しました。

2024-03-27 03:28 UTC, cyndiii29 commented on main.js
> +    this.APIKEY = '16806dd9a591b25a5beebeb69dd718b8';
それは、あとで指摘しようと思っていたポイントですね

2024-03-27 03:31 UTC, cyndiii29 commented on main.js
> +  // 複数の候補が返って来た場合はユーザーに選択させる方法がベストと考えた
> APIを試した挙動の結果を残す

必要ないですね！
APIのドキュメントみればわかりますし！

2024-03-27 03:37 UTC, cyndiii29 commented on main.js
> +      if (location.local_names && location.local_names.ja) {
良いコメントですね！

またその意図を汲み取るなら
```suggestion
      if (location.local_names.ja) {
        // 日本語都市名
      }
      else if (location.location_names) {
          // 日本語じゃない都市名
      }
      else {
          // location
      }
```

これのほうがよくないですか？？
@KenJamesHioki

2024-03-27 03:51 UTC, cyndiii29 commented on main.js
> +  _extractLocInfo(locName, locInfo) {
[nits]
こちらの関数ですが、関数としての内容が薄すぎますね
location渡してそのなかでextractしてもらいましょうよ
extractってなまえなんだから

```suggestion
  _extractLocInfo(location) {
      if (location.local_names.ja) {
        // 日本語都市名
      }
      else if (location.location_names) {
          // 日本語じゃない都市名
      }
      else {
          // location
      }
    
  }
```

2024-03-27 05:31 UTC, cyndiii29 commented on main.js
> +    const multiLocUni = multiLocMap.map(location => location[1]);
[Q]
これ何してるんですか？？
multiLocとmultiLocUniだと中身の変化ってありますかね？？

2024-03-27 05:50 UTC, cyndiii29 reviewed
[IMO]
せっかくつくったからレスポンシブ対応したくないですか、、？？

![スクリーンショット 2024-03-27 14 45 32](https://github.com/KenJamesHioki/weather_app/assets/28001966/a45fbf62-32a4-4cbb-ad34-9c34cd0543c0)

2024-03-28 05:46 UTC, KenJamesHioki commented on main.js
> +  _init() {
クラス内の変数やメソッドは極力プライベートにするのが良いとされている。
理由としては、プライベート化していないと外部から直接アクセスができてしまい意図せず変数の値が書き換わってしまうリスクがあるから。そのため変数は基本的にプライベート化し、値のsetやgetをしたい場合はメソッド経由にし、直接的な関与を避ける。

メソッドに関しても同様のことが言える。
外部との橋渡し役のメソッドは限定し、それ以外のメソッドは意図せず呼ばれないようプライベート化するのが安全。

_と#の違い
最新のJavascriptでは#を付けることで変数やメソッドをプライベート化できる。外部からアクセスしようとするとエラーが発生する。
_は#が登場する前にあった記法で、飽くまで明示的にプライベートであることを他の開発者に伝える方法である。#とは異なり、実際にアクセスしようとすればできてしまう。
上記の内容により、最近では#を使うことが推奨されている。

2024-03-28 06:13 UTC, KenJamesHioki commented on main.js
> +      if (location.local_names && location.local_names.ja) {
@cyndiii29 
コード内の僕のコメントがミスリードする内容だったので、まずは訂正させてください。

//都市の日本語名が表示可能な場合は日本語名の表示を優先するための分岐

と書いていますが、正しくは、

//都市の日本語名が表示可能な場合は日本語名の表示を優先し、なければ必ず英語名をするための分岐

更に追加情報：
locationオブジェクトにはlocal_namesがある場合とない場合がある。
local_namesが存在する場合でも、ja（日本語名）がある場合とない場合がある。また英語名もある場合とない場合がある。

そのため、local_namesがある&&ja（日本語名）がある場合は、その日本語名を取得。
ない場合は英語名が担保されているnameを取得するように実装をしています。

2024-03-28 06:43 UTC, KenJamesHioki commented on main.js
> +  _extractLocInfo(locName, locInfo) {
@cyndiii29 
条件分岐や必要情報の抽出を_extractLocInfo内にまとめました。
引数としてlocationのみを渡すように改修しています。

2024-03-28 06:45 UTC, KenJamesHioki commented on main.js
> +    const multiLocUni = multiLocMap.map(location => location[1]);
[A]
これは重複している都市名を排除するために実行しています。

objという変数が不適切のため、locationに変更しました。
また_getMultiLocationNames内で実行すると分かりづらいので、_removeDuplicateLocsというメソッドを別で作りました。

2024-03-28 06:46 UTC, KenJamesHioki commented
> [IMO] せっかくつくったからレスポンシブ対応したくないですか、、？？

[A]
レスポンシブ対応で実装しましたが、バグですね。
ちゃんと表示されるように改修します。

2024-03-28 07:40 UTC, KenJamesHioki commented on main.js
> +    this.APIKEY = '16806dd9a591b25a5beebeb69dd718b8';
@cyndiii29 
https://github.com/KenJamesHioki/weather_app/pull/16#discussion_r1538916895
ここで共有した手法はJavascriptで開発をしているときには使えなかったため、一旦はapikeys.jsという別ファイルを作って、APIキーをそこに格納してmain.jsから呼び出すようにしています。

※注意
apikeys.jsはgitignoreに追加しているため、git上では管理していません。
APIキーが必要な場合は連絡ください。

2024-03-28 07:43 UTC, KenJamesHioki commented
@cyndiii29 
> [IMO] せっかくつくったからレスポンシブ対応したくないですか、、？？

スマホの場合は天気情報が縦に並ぶレイアウトに変更しました。
所々フォントサイズは少し小さめにし、バランスを整えています。
<img width="311" alt="スクリーンショット 2024-03-28 16 41 06" src="https://github.com/KenJamesHioki/weather_app/assets/43932622/62354fd5-5aca-4b78-aab5-cbee34cd0322">

2024-03-28 14:46 UTC, KenJamesHioki commented
@cyndiii29 
https://github.com/KenJamesHioki/weather_app/pull/16/commits/10afef469bc2efef7efa826826863082e4995c6d

メソッド名、変数名を改変してみました。
少しはわかりやすくなったと思います。

次はメソッドの責務を絞って、メソッド名と責務が釣り合うように改善してみます。

2024-03-29 05:00 UTC, cyndiii29 commented on main.js
> +      return;
[IMO]
エラーコードをユーザーが出されても困惑するからそれだったら出さない方がいいとおもいます。
errorログに出力しておくでよいのかなと！

2024-03-29 05:10 UTC, cyndiii29 commented on main.js
> +      if (location.local_names && location.local_names.ja) {
[IMO]
なるほどですね！
その旨はコードにコメントしておかないと、他のエンジニアも同じ勘違いをする可能性があるので書いてある方が個人的には良いのかなと思いました！

2024-03-29 05:27 UTC, cyndiii29 commented on main.js
> +  }
```suggestion
  //都市名が重複してAPIから返却される場合があるので、事前に重複を排除する
  _removeDuplicateLocations(locations) {
    const uniqueLocationsMap = Array.from(new Map(multiLoc.map(location => [location.name, location])));
    return uniqueLocationsMap.map(location => location[1]);
  }
```
僕ならこうするを書いておきます
- コメントもうちょい踏み込んでwhyをかく
- メソッド名はシンプルにできるはず。難しいメソッドは難しいことしているべきで、これって非常に単純なことしてるだけだよね？

2024-03-29 05:28 UTC, cyndiii29 commented on main.js
> +  }
[MUST]
```
const uniqueLocationsMap = Array.from(new Map(multiLoc.map(location => [location.name, location])));
```
この結果はMapではないので嘘ついてます。確認して実装してください。

2024-03-29 05:30 UTC, cyndiii29 commented on main.js
> +  }
```
uniqueLocationsMap.map(location => location[1]);
```
重複を排除する以外のこともやってませんかね？

2024-03-29 10:16 UTC, KenJamesHioki commented
@cyndiii29 

https://github.com/KenJamesHioki/weather_app/pull/16/commits/d3e7bfd8a807b40e37435288e73c8ec625cd43fd
https://github.com/KenJamesHioki/weather_app/pull/16/commits/5bb2d8039a52ade0c8248d9f9f1b4220582686c0

全体的にリファクタリングを行いました。
・new WeatherAppのトリガーをクラス外に移動
・関数の責務を小さくし、それぞれの実行内容に応じて別の関数を作成
・命名を変更
・ブロックごとに改行を追加

2024-03-29 10:27 UTC, KenJamesHioki commented on main.js
> +  }
@cyndiii29 
https://github.com/KenJamesHioki/weather_app/commit/d3e7bfd8a807b40e37435288e73c8ec625cd43fd

[変更点]
・コメント内容の変更
・メソッド名の変更
・uniqueLocationsMapの命名変更

[IMO]
> ```
> uniqueLocationsMap.map(location => location[1]);
> ```
> 
> 重複を排除する以外のこともやってませんかね？
メソッドの引数と同じ形式でreturnをしているので問題ないと考えています。

一個前のコードで
`const uniqueLocationsMap = Array.from(new Map(multiLoc.map(location => [location.name, location])));
`
形式を変えてしまっているので、returnする前に形式を戻してあげています。

2024-03-29 10:28 UTC, KenJamesHioki commented on main.js
> +    const multiLocUni = multiLocMap.map(location => location[1]);
@cyndiii29 
こちらの内容と重複しているので、このスレッドはResolveに変更しても良いですか？
https://github.com/KenJamesHioki/weather_app/pull/16#discussion_r1544336705

2024-03-29 14:35 UTC, cyndiii29 commented on error_class.js
> +}
エラーのclassをせっかく作ったのでそれぞれの凝集性をあげていきたいですね
いままだすっからかんです。なにか、それぞれのエラーにはやせそうなメソッドはないでしょうか？
(ヒント)
ErrorHandlerのなかのどこか

2024-03-30 04:08 UTC, cyndiii29 reviewed
メソッドの凝集性があがって見通しがよくなってきましたね！
ここでいったん細かい指摘しておきます！

2024-03-30 04:08 UTC, cyndiii29 commented on main.js
> +  _chooseSuggestion() {
[nits]
このメソッドは提案を選んでいるのではなく、ユーザーが選ぶ選択肢を作成してますよね？？

2024-03-30 04:08 UTC, cyndiii29 commented on main.js
> +    const suggestions = document.querySelectorAll('.weather__li');
[IMO]
ぱっとみ何の提案かわからないですね！
場所の提案だと思うのでsuggested〇〇みたいな形の方がわかりやすいと思います

2024-03-30 04:08 UTC, cyndiii29 commented on main.js
> +  }
処理のながれわかりやすいやん、ええやん

2024-03-30 04:08 UTC, cyndiii29 commented on main.js
> +  _checkLocationNumbers(locationDetails) {
[nits]
いろんなことをやりすぎているのでこのメソッドに名前をつけるのはやや難しそうです

```
      const allLocations = this._getAllLocation(locationDetails);
      const uniqueLocations = this._removeDuplicateLocations(allLocations);
```
この処理は果たして `locationDetails.length >= 2` の条件の時にやらないといけないのでしょうか？
そうでない場合、不必要な条件分岐を見つけることができそうです

2024-03-30 04:08 UTC, cyndiii29 commented on main.js
> +    const suggestions = document.querySelectorAll('.weather__li');
もっと言うとweather__liではないかもなぁ
表示するのは天気じゃないですもんね

2024-04-01 08:35 UTC, KenJamesHioki commented on main.js
> +    const suggestions = document.querySelectorAll('.weather__li');
@cyndiii29 
https://github.com/KenJamesHioki/weather_app/commit/fb94e160bbcc428a11d91d6011a7cd1ea63a1b93

以下の2点を実施しました。
・メソッド名の変更
・候補地の表示に関連する要素のクラス名を変更

2024-04-01 08:40 UTC, cyndiii29 commented on main.js
> +    const suggestions = document.querySelectorAll('.weather__li');
TODOコメントも消せませんかね？

2024-04-01 08:45 UTC, KenJamesHioki commented on main.js
> +  _chooseSuggestion() {
https://github.com/KenJamesHioki/weather_app/pull/16/commits/1b6f7468f1839f65890e7715e5811b1b39240bf7
・メソッド名をonSuggestedLocationClickに変更

2024-04-01 08:45 UTC, KenJamesHioki commented on main.js
> +    const suggestions = document.querySelectorAll('.weather__li');
https://github.com/KenJamesHioki/weather_app/pull/16/commits/4a099ec91b49583f3980d0e55c996af5c2c86e85
消しました。

2024-04-01 08:47 UTC, KenJamesHioki commented on error_class.js
> +}
@cyndiii29 
https://github.com/KenJamesHioki/weather_app/pull/16/commits/fad874883dd9fa6f4475dba85d746ec860fb6588
・innerHtmlを生成する内容を各クラス内で定義
・ErrorHandler内ではそのinnerHtmlを受け取るのみに変更

2024-04-01 08:47 UTC, cyndiii29 commented on main.js
> +  _chooseSuggestion() {
まあいいでしょう！

2024-04-01 09:00 UTC, cyndiii29 commented on main.js
> +      new ErrorHandler(e);
[MUST]
ErrorHandlerくんを複数箇所でnewしているのですが、その必要はまったくないです。
ErrorHandlerくんを一体召喚して、そいつを使い回すように実装してみましょう
クラスの理解につながります

@KenJamesHioki

2024-04-01 09:07 UTC, KenJamesHioki commented on main.js
> +  _checkLocationNumbers(locationDetails) {
`locationDetails.length >= 2`だとしても、重複しているlocationを排除した後に結果が1であれば天気情報の表示に移行したい。
そのため、
```
const allLocations = this._getAllLocation(locationDetails);
const uniqueLocations = this._removeDuplicateLocations(allLocations);
```
ここでuniqueLocationsの数を出しています。

2024-04-01 09:16 UTC, cyndiii29 commented on main.js
> +    }
[Q]
オブジェクトにわざわざ格納する意味ってありますか？？

2024-04-01 10:56 UTC, cyndiii29 commented on main.js
> +    }
[IMO]
length === 1の重複を取り除きたいので、僕ならこうしますね

メソッドの中身をさっぱりさせることで
- 場所が特定できたら、APIを叩きに行く
- そうでない場合は複数都市の情報をとりに行けるようにする

というこのメソッドの役目がみえますね

```suggestion
    const locationInfos = this._removeDuplicateLocations(locationDetails.map(location => this._extractLocationInfo(location))) ;
       
    if (!locationInfos.length) {
      throw new ErrorNoCity('都市が見つかりませんでした。')
    }
    
    if (locationInfos.length === 1) {
      const coordinates = {
        lat: locationInfos[0].lat,
        lon: locationInfos[0].lon,
      }
      this._getWeather(coordinates);
    } else {
        this._renderLocationSuggestions(locationInfos);
      }
    }
```

2024-04-01 11:44 UTC, cyndiii29 commented on error_class.js
> +    this.name = "Client Error";
[nits]
名前をクラスに持たせるようにしていますが、すでに`ClientError`という立派な名前を既に持ってませんかね？？

2024-04-03 08:33 UTC, KenJamesHioki commented on main.js
> +    }
確かに・・・！
これは一個ずつ別々の定数に入れてあげればいいですね。
（定数に入れた方が何を扱っているのかがわかりやすいので定数には入れるようにします。）

2024-04-03 08:56 UTC, KenJamesHioki commented on main.js
> +    }
先にユニークなLocationsにすることで`locationInfos.length === 1`の分岐を一回分省けるというわけですね。
圧倒的に提案してもらった方がいいですね。

2024-04-03 09:06 UTC, KenJamesHioki commented on main.js
> +  _checkLocationNumbers(locationDetails) {
https://github.com/KenJamesHioki/weather_app/pull/16#discussion_r1546213758

別スレッドで同じ内容を扱っているためResolveに変更。

2024-04-03 09:15 UTC, KenJamesHioki commented on main.js
> +      new ErrorHandler(e);
@cyndiii29 

https://github.com/KenJamesHioki/weather_app/pull/16/commits/938a7f95e061db69270f529e661ed7961d54c5cf

変更点
・WeatherAppのconstructor内でErrorHandlerをnewする
・ErrorHandlerクラス内にcatchErrorメソッドを新しく作ってthis.#errorの更新とその後の処理を任せる
・WeatherApp内でエラーを拾うとcatchErrorメソッドで処理する

2024-04-03 09:16 UTC, KenJamesHioki commented on main.js
> +    }
https://github.com/KenJamesHioki/weather_app/pull/16/commits/c5d60f01d7ac494da7d2cab38e35c252e2b15571

こちらで修正

2024-04-03 09:17 UTC, KenJamesHioki commented on error_class.js
> +    this.name = "Client Error";
https://github.com/KenJamesHioki/weather_app/pull/16/commits/6594c0ca09403e9ea62a7697a29addc4c0f028ce

constructor.nameでコンストラクタ名が取得できることがわかったので、それぞれのnameにはconstructor.nameを代入する変更を加えた。

2024-04-03 09:20 UTC, KenJamesHioki commented on main.js
> +    }
https://github.com/KenJamesHioki/weather_app/pull/16/commits/ff452b379113c280ba2cbaec864afcc6e7f53721

[IMHO]
この2行を最初に持ってきて、`uniqueLocations.length`に対して分岐をするようにしました。
```
const allLocations = this._getAllLocation(locationDetails);
const uniqueLocations = this._removeDuplicateLocations(allLocations);
```
分岐の手順は提案してもらった方法を採用させてもらいました。

2024-04-03 10:12 UTC, cyndiii29 commented on main.js
> +    }
定数というか変数ですね！

2024-04-03 10:14 UTC, cyndiii29 commented on main.js
> +      new ErrorHandler(e);
ないす！

2024-04-03 16:35 UTC, cyndiii29 commented on error_class.js
> +    this.name = this.constructor.name;
本当にこれ使われてますかね？？実装ミアタラナイ、、、

2024-04-03 16:39 UTC, cyndiii29 commented on main.js
> +        throw new Error('処理ができませんでした。');
```suggestion
      case 400, 401, 404, 429:
        throw new ClientError('エラーコード：${status}');
      case 500, 502, 503, 504:
        throw new ServerError('エラーコード：${status}');
      default:
        throw new Error('予期せぬエラーが発生しました エラーコード: ${status}');
```

2024-04-04 07:01 UTC, KenJamesHioki commented on main.js
> +        throw new Error('処理ができませんでした。');
その通りだと思います。

https://github.com/KenJamesHioki/weather_app/pull/16/commits/ef8edb45159136696f1cbaf3fd9ef0aeb2639947
こちらで変更済み。

2024-04-04 07:02 UTC, KenJamesHioki commented on error_class.js
> +    this.name = this.constructor.name;
https://github.com/KenJamesHioki/weather_app/pull/16#discussion_r1550088859
ここのコードでnewをしています。
そういうことではなく？

2024-04-04 07:03 UTC, KenJamesHioki commented
@cyndiii29 
https://github.com/KenJamesHioki/weather_app/pull/16/commits/895b39b655132b0a16a6a2764619618bc5ef47ec

WeatherAppクラスの凝集性を上げるためにLoaderクラスを別で作りました。

2024-04-04 13:18 UTC, cyndiii29 commented on error_class.js
> +    this.name = this.constructor.name;
このclassはnameを変数にもっていると思うのですが、このnameという変数はどこにも参照されないですよね？？
@KenJamesHioki

2024-04-04 13:20 UTC, cyndiii29 commented on main.js
> +        throw new Error('処理ができませんでした。');
![Simon Thumb Well Done](https://media1.giphy.com/media/Zcm5DaspYzhTxstkF4/giphy.gif?cid=47028fa8os12vpsu0fw6byc1uovg9d0dhsg5w5gd25oowbw5&ep=v1_gifs&rid=giphy.gif&ct=g)

2024-04-04 13:23 UTC, cyndiii29 commented on error_class.js
> +    this.name = this.constructor.name;
以下のような使われ方してないですよね？？
なんのためにこの`name`は必要なんでしょう？？
```
const clientError = new ClientError('message');

const errorMessage = `エラーが発生しました ${clientError.name}`
```

2024-04-04 13:45 UTC, KenJamesHioki commented on error_class.js
> +    this.name = this.constructor.name;
@cyndiii29
ErrorHandlerクラス内で`console.error(this.#error)`を呼んでいて、そのときにコンソールにnameを表示するために`this.name = this.constructor.name`としています。
このクラスのインスタンスであればClientError:〜となるようにしています。

2024-04-04 16:23 UTC, cyndiii29 commented on error_class.js
> +    this.name = this.constructor.name;
あーそうゆうことか
わかりにくいっすね

2024-04-04 16:32 UTC, cyndiii29 reviewed
ほぼ最後の指摘にします

2024-04-04 16:32 UTC, cyndiii29 commented on error_class.js
> +  }
constructorにerrorを要求しているけど、実際には使ってないよね？
```
new ErrorHandler()
```
ってインスタンス化してるのに
理解してるか怪しいです

2024-04-04 16:32 UTC, cyndiii29 commented on error_class.js
> +  #error;
これはなんですか？？

2024-04-04 16:38 UTC, cyndiii29 commented on error_class.js
> +  catchError(e) {
catchしてますか？？

2024-04-04 16:49 UTC, cyndiii29 commented on error_class.js
> +  }
呼び名って定数なので、staticってやつで定義するのがええんやないかな
そして定数はconstructorで定義するものではないです
```suggestion
class ClientError extends Error {
  static ErrorName = 'Client Error'

  constructor(message) {
    super(message);
  }
```

2024-04-05 08:35 UTC, KenJamesHioki commented on error_class.js
> +  }
その通りですね。
ErrorHandlerをnewするタイミングを前回のコミットで変えたのでそれに合わせてこの部分も変更しないとでした。
newするときに引数はもう渡していないので、constructorは消しておきます。
errorはプライベートプロパティとしてクラスの上に宣言だけしておきます。

2024-04-05 08:42 UTC, KenJamesHioki commented on error_class.js
> +  catchError(e) {
ErrorHandler内のメソッドはtriggerとdisplayに変更しておきます。

2024-04-05 13:42 UTC, KenJamesHioki commented on error_class.js
> +  }
https://github.com/KenJamesHioki/weather_app/pull/16/commits/a9b68bd0bd89393b07403decfaf7f6a7d7f1ba1c
エラーの名前を表示することは不必要だと感じたため、クラス内でnameプロパティを扱うことをやめました。
エラーメッセージとstatusコードのみをコンソールに表示する実装に変更しました。

2024-04-05 13:45 UTC, KenJamesHioki commented on error_class.js
> +  #error;
https://github.com/KenJamesHioki/weather_app/pull/16/commits/a9b68bd0bd89393b07403decfaf7f6a7d7f1ba1c
`#error`にエラーオブジェクトを格納していましたが、インスタンス化したときにエラーオブジェクトを持っておく必要はないので、コードから排除しました。

2024-04-05 13:45 UTC, KenJamesHioki commented on error_class.js
> +  catchError(e) {
https://github.com/KenJamesHioki/weather_app/commit/a9b68bd0bd89393b07403decfaf7f6a7d7f1ba1c
メソッド名を改変しました。

2024-04-05 13:46 UTC, KenJamesHioki commented on error_class.js
> +  }
https://github.com/KenJamesHioki/weather_app/commit/a9b68bd0bd89393b07403decfaf7f6a7d7f1ba1c
constructorを削除済み。

2024-04-08 07:59 UTC, cyndiii29 approved these changes
![Miyagi LGTM](https://media2.giphy.com/media/59DEtWl4ZuhexpRRrP/giphy.gif?cid=47028fa8os12vpsu0fw6byc1uovg9d0dhsg5w5gd25oowbw5&ep=v1_gifs&rid=giphy.gif&ct=g)

2024-04-10 10:17 UTC, merged